export default (function() {
    const textos = {
        parrafo1: 'Ahora que sabemos que existen muchos lenguajes de programación, empezaremos conociendo un poco acerca del lenguaje C, así como también del C++.',
        parrafo2: 'El lenguaje C es uno de los lenguajes de programación más antiguos usados en la actualidad, ya que fue desarrollado por el informático Dennis M. Ritchie entre los años de 1969 y 1972 y es considerado como un lenguaje poderoso, además de flexible ya que existe una gran variedad de proyectos que se pueden realizar con él, por ejemplo, estoy hablando de hojas de cálculo, compiladores para otros lenguajes de programación, sistemas operativos, aplicaciones o gráficos.',
        parrafo3: 'Este lenguaje es uno de los más populares por las características con las que cuenta, como por ejemplo que es bastante amigable con el programador pues nos permite escribir programas y entablar una conversación con la computadora de una manera muy sencilla ya que es un lenguaje de pocas palabras pero contiene solo algunas palabras clave que son como su base, además, las cosas que podemos lograr con el lenguaje C no tienen límite, el único límite es nuestra imaginación y también cuenta con una ventaja, estoy hablando de que es un lenguaje transportable, es decir, si el programador escribe un programa en una computadora de la marca que más le guste, después ese mismo programa puede ser utilizado en otra computadora con otro sistema diferente realizando tal vez pocas o ninguna modificación a nuestro programa.',
        parrafo4: 'Estas características permiten que esté disponible en muchas plataformas, incluso más que cualquier otro lenguaje en el mundo y es por ello que es muy querido, además de la versatilidad con la que cuenta y la eficiencia en los códigos que se crean, es por ello que el lenguaje C es una excelente alternativa para que sea el primer lenguaje de programación que aprendas.',
        parrafo5: 'Pero no todo termina ahí, pues con el paso de los años se creó un nuevo lenguaje llamado C ++ y tal vez a tu mente vengan preguntas como; ¿Qué significa? o ¿Tiene relación con el lenguaje C? pero no te preocupes, aquí te ayudamos a comprenderlo. ',
        parrafo6: 'Pues bien, el lenguaje C ++ (pronunciado como C plus plus ó C más más) es una versión mejorada del C, lo cual nos quiere decir que C ++ contiene todo lo que  tiene C pues toma la base de este lenguaje, lo que hace diferente a C ++ es que este es un lenguaje de programación orientado a objetos, es decir, se trata de una forma en la que nosotros podemos resolver una problemática de nuestra vida cotidiana por ejemplo, mediante el uso de objetos que en programación estos son variables llamadas atributos y las acciones que puede realizar un objeto las llamaremos método.',
        parrafo7: 'Entonces en resumen, el lenguaje C ++ es usado para lo mismo que C, pero con la diferencia de que C ++ es más potente y busca resolver problemáticas usando objetos con diferentes métodos, en ese sentido, podemos decir que el C ++ es un lenguaje híbrido y podemos agregar también que la mayoría de los videojuegos y aplicaciones más famosas están programados con este lenguaje lo cual nos hace darnos cuenta de la importancia que ha tenido no solo este, sino ambos lenguajes a partir de su creación y para finalizar solo me queda decir que hay que tomar en cuenta que aprendiendo uno, automáticamente ya estás aprendiendo el otro y las utilidades que les puedes dar no tienen límites.'
    }
    return textos
})